import { MD3LightTheme, MD3DarkTheme, type MD3Theme } from 'react-native-paper';
import { colors, neutral, darkNeutral, semantic, darkSemantic, borderRadius } from './tokens';

export const lightTheme: MD3Theme = {
  ...MD3LightTheme,
  roundness: borderRadius.sm / 2,
  colors: {
    ...MD3LightTheme.colors,
    primary: colors.primary,
    onPrimary: '#FFFFFF',
    primaryContainer: semantic.selectedLight,
    onPrimaryContainer: colors.primaryActive,
    secondary: colors.secondary,
    onSecondary: '#FFFFFF',
    secondaryContainer: neutral[100],
    onSecondaryContainer: neutral[800],
    tertiary: colors.info,
    onTertiary: '#FFFFFF',
    tertiaryContainer: '#E0EDF5',
    onTertiaryContainer: '#1A3A4F',
    error: colors.error,
    onError: '#FFFFFF',
    errorContainer: colors.errorBg,
    onErrorContainer: colors.error,
    background: semantic.background,
    onBackground: neutral[900],
    surface: semantic.surface,
    onSurface: neutral[900],
    surfaceVariant: neutral[100],
    onSurfaceVariant: neutral[600],
    outline: neutral[300],
    outlineVariant: neutral[200],
    inverseSurface: neutral[800],
    inverseOnSurface: neutral[50],
    inversePrimary: '#E8C8CC',
    shadow: '#000000',
    scrim: 'rgba(0, 0, 0, 0.3)',
    surfaceDisabled: `rgba(17, 24, 39, 0.12)`,
    onSurfaceDisabled: `rgba(17, 24, 39, 0.38)`,
    backdrop: semantic.overlayDark,
    elevation: {
      level0: 'transparent',
      level1: semantic.surface,
      level2: semantic.surfaceElevated,
      level3: neutral[50],
      level4: neutral[100],
      level5: neutral[200],
    },
  },
};

export const darkTheme: MD3Theme = {
  ...MD3DarkTheme,
  roundness: borderRadius.sm / 2,
  colors: {
    ...MD3DarkTheme.colors,
    primary: colors.primary,
    onPrimary: '#FFFFFF',
    primaryContainer: darkSemantic.selectedLight,
    onPrimaryContainer: '#E8C8CC',
    secondary: colors.secondary,
    onSecondary: '#FFFFFF',
    secondaryContainer: darkNeutral[200],
    onSecondaryContainer: darkNeutral[800],
    tertiary: colors.info,
    onTertiary: '#FFFFFF',
    tertiaryContainer: '#1A3A4F',
    onTertiaryContainer: '#B8D4E8',
    error: colors.error,
    onError: '#FFFFFF',
    errorContainer: 'rgba(184, 82, 76, 0.12)',
    onErrorContainer: '#F0A8A4',
    background: darkSemantic.background,
    onBackground: darkNeutral[900],
    surface: darkSemantic.surface,
    onSurface: darkNeutral[900],
    surfaceVariant: darkNeutral[200],
    onSurfaceVariant: darkNeutral[600],
    outline: darkNeutral[300],
    outlineVariant: darkNeutral[200],
    inverseSurface: darkNeutral[900],
    inverseOnSurface: darkNeutral[50],
    inversePrimary: colors.primary,
    shadow: '#000000',
    scrim: 'rgba(0, 0, 0, 0.5)',
    surfaceDisabled: 'rgba(249, 250, 251, 0.12)',
    onSurfaceDisabled: 'rgba(249, 250, 251, 0.38)',
    backdrop: darkSemantic.overlayDark,
    elevation: {
      level0: 'transparent',
      level1: darkSemantic.surface,
      level2: darkSemantic.surfaceElevated,
      level3: darkNeutral[200],
      level4: darkNeutral[300],
      level5: '#444444',
    },
  },
};
