/**
 * Generate Swift board placement constants for the iOS native BLE layer.
 *
 * This script reads the committed TypeScript constants produced by
 * generate-board-constants.ts, so it can be run independently when only the
 * Swift output needs to be refreshed.
 */

import { mkdirSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';
import { LED_PLACEMENTS } from '../src/generated/led-placements-data';
import { HOLE_PLACEMENTS } from '../src/generated/product-sizes-data';

const scriptDir = fileURLToPath(new URL('.', import.meta.url));
const outputPath = join(scriptDir, '../../../mobile/ios/App/App/BoardPlacementData.swift');

type PlacementTuple = [number, number | null, number, number];

function buildMirroredPlacements(): Record<string, Record<string, Record<string, number>>> {
  const mirroredPlacements: Record<string, Record<string, Record<string, number>>> = {};

  for (const [boardName, boardPlacements] of Object.entries(HOLE_PLACEMENTS)) {
    mirroredPlacements[boardName] = {};

    for (const [layoutSetKey, placements] of Object.entries(boardPlacements)) {
      const [layoutId] = layoutSetKey.split('-');
      mirroredPlacements[boardName][layoutId] ??= {};

      for (const [placementId, mirroredPlacementId] of placements as PlacementTuple[]) {
        if (mirroredPlacementId !== null) {
          mirroredPlacements[boardName][layoutId][String(placementId)] = mirroredPlacementId;
        }
      }
    }
  }

  return mirroredPlacements;
}

function stableStringify(value: unknown): string {
  return JSON.stringify(value);
}

function generateSwiftFile(): string {
  const ledPlacementsJson = stableStringify(LED_PLACEMENTS);
  const mirroredPlacementsJson = stableStringify(buildMirroredPlacements());

  return `// DO NOT EDIT THIS FILE MANUALLY
//
// This file is auto-generated by running:
//   node --import tsx packages/board-constants/scripts/generate-ios-board-placement-data.ts
//
// Aurora board placement data for the native iOS BLE layer.

import Foundation

enum BoardPlacementData {
    private static let ledPlacementsJSON = """
${ledPlacementsJson}
"""

    private static let mirroredPlacementsJSON = """
${mirroredPlacementsJson}
"""

    private static let ledPlacements: [String: [String: [String: Int]]] = decode(ledPlacementsJSON)
    private static let mirroredPlacements: [String: [String: [String: Int]]] = decode(mirroredPlacementsJSON)

    static func getLedPlacements(boardName: String, layoutId: Int, sizeId: Int) -> [Int: Int] {
        let key = "\\(layoutId)-\\(sizeId)"
        guard let placements = ledPlacements[boardName]?[key] else { return [:] }
        return placements.reduce(into: [:]) { result, entry in
            if let placementId = Int(entry.key) {
                result[placementId] = entry.value
            }
        }
    }

    static func mirroredPlacementId(boardName: String, layoutId: Int, placementId: Int) -> Int? {
        mirroredPlacements[boardName]?["\\(layoutId)"]?["\\(placementId)"]
    }

    private static func decode(_ json: String) -> [String: [String: [String: Int]]] {
        guard let data = json.data(using: .utf8),
              let decoded = try? JSONDecoder().decode([String: [String: [String: Int]]].self, from: data)
        else {
            return [:]
        }
        return decoded
    }
}
`;
}

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, generateSwiftFile(), 'utf-8');
console.info(`Wrote ${outputPath}`);
